--[[ AIOS_MicroBench.lua (condensed) ]]--
local _G=_G; AIOS=_G.AIOS or {}; local MB={lastReport=""}; AIOS.MicroBench=MB
local function Dlog(l,t,m) if AIOS and AIOS.Debug and AIOS.Debug.Log then AIOS.Debug:Log(l or "info", t or "Bench", m) end end
local function now() if _G.GetTimePreciseSec then return _G.GetTimePreciseSec() end if _G.debugprofilestop then return _G.debugprofilestop()/1000 end return (_G.GetTime and _G.GetTime()) or 0 end
local function bench_event(n) local EB=(AIOS and (AIOS.EventBus or AIOS.SignalHub)) or nil; if not (EB and (EB.Emit or EB.Trigger)) then return "EventBus not available." end local emit=EB.Emit or EB.Trigger local evt="AIOS_BENCH_EVT"; local count=0; for _,m in ipairs({"Listen","On","Add","Register","Subscribe"}) do local f=EB[m]; if type(f)=="function" then pcall(f,EB,evt,function(...) count=count+1 end); break end end local t0=now(); for i=1,n do emit(EB,evt) end local dt=now()-t0; return string.format("EventBus.Emit x%d  total=%.6f  per=%.9f  hits=%d", n, dt, dt/n, count) end
local function bench_serializer(n) local S=AIOS and AIOS.Serializer; if not (S and S.Serialize and S.Deserialize) then return "Serializer not available." end local p={a=123,b="hello",c=true,d={1,2,3,4,5},e={foo="bar",z={x=1,y=2}}}; local times={} for i=1,n do local t0=now(); local s,err=S:Serialize(p); if not s then return "Serialize failed: "..tostring(err) end local ok,out=S:Deserialize(s); if not ok then return "Deserialize failed." end times[#times+1]=now()-t0 end local min,max,sum=times[1],times[1],0 for i=1,#times do local v=times[i]; if v<min then min=v end if v>max then max=v end sum=sum+v end local avg=sum/#times return string.format("Serializer roundtrip (%d)  min=%.6f  avg=%.6f  max=%.6f (sec)", #times, min, avg, max) end
local function run_suite(w,i) w=(w or "all"):lower(); i=tonumber(i or 0) or 0; if i<=0 then i=(w=="serializer") and 300 or 5000 end if i>100000 then i=100000 end local lines={} if w=="event" or w=="all" then lines[#lines+1]=bench_event(i) end if w=="serializer" or w=="all" then lines[#lines+1]=bench_serializer((w=="all") and math.floor(i/10) or i) end local rep=table.concat(lines,"\n"); MB.lastReport=rep; Dlog("info","Bench","\n"..rep); return rep end
local function export() local text=MB.lastReport or ""; if text=="" then text="(no report yet; run /aiosbench)" end if _G.AIOS_CopyBox and _G.AIOS_CopyBox.Open then _G.AIOS_CopyBox.Open(text); return end local f=CreateFrame("Frame","AIOS_BenchExport",UIParent,"BackdropTemplate"); f:SetSize(560,320); f:SetPoint("CENTER"); f:SetBackdrop({bgFile="Interface\\Buttons\\WHITE8x8",edgeFile="Interface/Tooltips/UI-Tooltip-Border",edgeSize=16,insets={left=4,right=4,top=4,bottom=4}}); f:SetBackdropColor(0,0,0,1); f:SetBackdropBorderColor(0.1,0.6,1,0.9); local scroll=CreateFrame("ScrollFrame",nil,f,"UIPanelScrollFrameTemplate"); scroll:SetPoint("TOPLEFT",12,-12); scroll:SetPoint("BOTTOMRIGHT",-12,12); if scroll.ScrollBar then scroll.ScrollBar:Hide(); scroll.ScrollBar.Show=function() end end local edit=CreateFrame("EditBox",nil,scroll); edit:SetMultiLine(true); edit:SetFontObject(ChatFontNormal or SystemFont_Shadow_Med1); edit:SetAutoFocus(false); edit:SetWidth(520); edit:SetText(text); scroll:SetScrollChild(edit); f:Show() end
_G.SLASH_AIOSBENCH1="/aiosbench"; SlashCmdList["AIOSBENCH"]=function(msg) local a={}; for w in tostring(msg or ""):gmatch("%S+") do a[#a+1]=w end local sub=(a[1] or ""):lower(); if sub=="" then run_suite("all") elseif sub=="export" then export() elseif sub=="run" then run_suite(a[2], a[3]) else Dlog("info","Bench","Usage: /aiosbench [run <event|serializer|all> <iters>] | export") end end
Dlog("info","Bench","AIOS_MicroBench ready. Use /aiosbench")
