--[[ AIOS_QATester.lua (condensed) ]]--
local _G=_G; AIOS=_G.AIOS or {}; local D=AIOS.Debug; local S=AIOS.Serializer; local SV=AIOS.Saved; local C=AIOS.Codec; local T=AIOS.Timers; local EB=AIOS.EventBus
local Tester={}; AIOS.QATester=Tester; local function log(l,t,m) if D and D.Log then D:Log(l,t,m) end end; local function assert_eq(a,b,n) if a~=b then error(n..": expected '"..tostring(b).."' got '"..tostring(a).."'",0) end end
local tests={}
tests["Serializer: roundtrip"]=function() if not S then return "skip: serializer missing" end local obj={a=1,b="x",c={1,2,3},d=true,e=nil}; local s,err=S:Serialize(obj); if not s then error(err or "serialize failed",0) end local ok,out=S:Deserialize(s); assert_eq(ok,true,"deserialize ok"); assert_eq(type(out),"table","out is table"); assert_eq(out.b,"x","str field"); assert_eq(out.c[3],3,"array index 3"); return "ok" end
tests["Saved: defaults + set/get"]=function() if not SV then return "skip: saved missing" end SV:RegisterSchema("QA",{n=1,nest={x=2}},{scope="profile",version=1}); assert_eq(SV:Get("QA","n"),1,"default n"); SV:Set("QA","n",7); assert_eq(SV:Get("QA","n"),7,"set n=7"); return "ok" end
tests["Codec: lzss + crc"]=function() if not C or not AIOS.Hash then return "skip: codec missing" end local data=string.rep("ABCD",64).."tail"; local framed=C:Compress(data,{codec="lzss"}); local out,err=C:Decompress(framed); assert_eq(out,data,"roundtrip"); local crc=AIOS.Hash.CRC32(out); if type(crc)~="number" then error("crc type",0) end return "ok" end
tests["Timers: After/Every"]=function() if not T then return "skip: timers missing" end local fired=0; T:Every(0.02,function() fired=fired+1 end,{now=true}); T:After(0.12,function() fired=fired+100 end); return "ok" end
tests["EventBus: listen/emit"]=function() if not EB then return "skip: eventbus missing" end local v=0; EB:Once("QA_SIG", function() v=v+1 end); EB:Emit("QA_SIG"); assert_eq(v,1,"once fired"); return "ok" end
_G.SLASH_AIOSTEST1="/aiostest"; SlashCmdList["AIOSTEST"]=function() local total,passed,skipped,failed=0,0,0,0; for name,fn in pairs(tests) do total=total+1; local ok,msg=pcall(fn); if ok and msg=="ok" then passed=passed+1; log("info","QATest","PASS "..name) elseif ok and type(msg)=="string" and msg:find("^skip") then skipped=skipped+1; log("debug","QATest","SKIP "..name.." "..msg) else failed=failed+1; log("error","QATest","FAIL "..name.." - "..tostring(msg)) end end log("info","QATester", string.format("Summary: %d total, %d pass, %d skip, %d fail",total,passed,skipped,failed)) end
log("info","QATester","AIOS_QATester ready. Use /aiostest")
