--[[ AIOS_TraceGlue.lua v1.0 ]]--
local _G=_G; AIOS=_G.AIOS or {}; local SCHEMA="CoreTrace"; local defaults={mode="off",event="",level="info",tag="Trace"}
local function dlog(m) if AIOS and AIOS.Debug and AIOS.Debug.Log then AIOS.Debug:Log("debug","TraceGlue",m) end end
local function have_tracer() return AIOS and AIOS.SignalTracer and _G.SlashCmdList and _G.SlashCmdList["AIOSTRACE"] end
local function apply_saved() local SV=AIOS and AIOS.Saved; if not (SV and SV.Get and have_tracer()) then return end local mode=SV:Get(SCHEMA,"mode") or defaults.mode local event=SV:Get(SCHEMA,"event") or defaults.event local level=SV:Get(SCHEMA,"level") or defaults.level local tag=SV:Get(SCHEMA,"tag") or defaults.tag _G.SlashCmdList["AIOSTRACE"]("level "..tostring(level)); if tag and tag~="" then _G.SlashCmdList["AIOSTRACE"]("tag "..tostring(tag)) end if mode=="wildcard" then _G.SlashCmdList["AIOSTRACE"]("on *") elseif mode=="event" and event~="" then _G.SlashCmdList["AIOSTRACE"]("on "..event) else _G.SlashCmdList["AIOSTRACE"]("off") end dlog(("TraceGlue applied: mode=%s event=%s level=%s tag=%s"):format(mode,tostring(event),level,tostring(tag))) end
local function save_current() local SV=AIOS and AIOS.Saved; local Tr=AIOS and AIOS.SignalTracer; if not (SV and SV.Set and Tr) then return end local mode="off"; local event=""; if Tr.enabled then if Tr.wildcard or (Tr.filters and Tr.filters["*"]) then mode="wildcard" else for k,v in pairs(Tr.filters or {}) do if v and k~="*" then event=k; mode="event"; break end end end end local level=Tr.level or "info"; local tag=Tr.tag or "Trace"; SV.Set(SV,SCHEMA,"mode",mode); SV.Set(SV,SCHEMA,"event",event); SV.Set(SV,SCHEMA,"level",level); SV.Set(SV,SCHEMA,"tag",tag); dlog(("TraceGlue saved: mode=%s event=%s level=%s tag=%s"):format(mode,tostring(event),level,tostring(tag))) end
local function ensure_schema() local SV=AIOS and AIOS.Saved; if SV and SV.RegisterSchema then pcall(function() SV:RegisterSchema(SCHEMA, defaults, {scope="profile", version=1}) end) end end
local f=CreateFrame("Frame"); f:RegisterEvent("ADDON_LOADED"); f:RegisterEvent("PLAYER_LOGIN"); f:RegisterEvent("PLAYER_LOGOUT"); f:SetScript("OnEvent",function(_,evt) if evt=="ADDON_LOADED" then ensure_schema() elseif evt=="PLAYER_LOGIN" then C_Timer.After(0.2, apply_saved) elseif evt=="PLAYER_LOGOUT" then save_current() end end)
if AIOS and AIOS.SignalHub and AIOS.SignalHub.Listen then AIOS.SignalHub:Listen("AIOS_Core_Ready", function() C_Timer.After(0.2, apply_saved) end) end
_G.SLASH_AIOSTRACECFG1="/aiostracecfg"; SlashCmdList["AIOSTRACECFG"]=function(msg) msg=tostring(msg or ""):lower(); if msg=="save" then save_current() elseif msg=="load" then apply_saved() elseif msg=="off" then local SV=AIOS and AIOS.Saved; if SV and SV.Set then SV:Set(SCHEMA,"mode","off"); SV:Set(SCHEMA,"event","") end if have_tracer() then _G.SlashCmdList["AIOSTRACE"]("off") end else dlog("Usage: /aiostracecfg save|load|off") end end
